<#
.SYNOPSIS
    Извлекает значения SchemaName из C# в машиночитаемый JSON для синхронизации справочника со кодом.

.PARAMETER RepoRoot
    Корень решения (содержит Autogenerated/Src). По умолчанию два уровня выше каталога tools.

.PARAMETER OutputPath
    Куда сохранить JSON (по умолчанию docs/reference/entity-schema-names.generated.json).
#>

[CmdletBinding()]
param(
    [string]$RepoRoot = '',
    [string]$OutputPath = ''
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $_docs = Split-Path (Split-Path $MyInvocation.MyCommand.Path -Parent) -Parent
    $RepoRoot = Split-Path $_docs -Parent
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $_docs = Split-Path (Split-Path $MyInvocation.MyCommand.Path -Parent) -Parent
    $OutputPath = Join-Path $_docs 'reference\entity-schema-names.generated.json'
}

$src = Join-Path $RepoRoot 'Autogenerated\Src'
if (-not (Test-Path -LiteralPath $src)) {
    throw "Autogenerated/Src not found: $src"
}

$names = New-Object System.Collections.Generic.HashSet[string]

Get-ChildItem -Path $src -Filter '*.cs' -Recurse -File | ForEach-Object {
    Select-String -LiteralPath $_.FullName -Pattern 'SchemaName\s*=\s*"([^"]+)"' -AllMatches | ForEach-Object {
        foreach ($m in $_.Matches) {
            [void]$names.Add($m.Groups[1].Value)
        }
    }
}

$sorted = @($names | Sort-Object)

$payload = [ordered]@{
    generatedAtUtc = [DateTime]::UtcNow.ToString('o')
    repositoryRootHint = $RepoRoot
    sourceGlob = 'Autogenerated/Src/**/*.cs'
    matchPattern = 'SchemaName = "{name}"'
    schemaNameCount = $sorted.Count
    schemaNames = $sorted
}

$dir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

$json = ($payload | ConvertTo-Json -Depth 10)
[System.IO.File]::WriteAllText($OutputPath, $json, [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $OutputPath ($($sorted.Count) unique schema name references)."
exit 0
